language: python
sudo: true

python:
    - "3.4"
    - "3.5"
    - "nightly"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq liblapack.so 

install:
    - pip install matplotlib==1.5.1 tbmodels
    - pip install .

# run tests
script: 
    - cd tests
    - py.test --no-plot-compare
